version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1225
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database/:/var/lib/mysql # -v 옵션 (디렉토리 마운트 설정)

# version: '3'
# services:
#   mysql:
#     image: mysql:8.0
#     ports:
#       - '3306:3306'
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#     restart: always
#     container_name: mysql

# 비밀번호 설정 순서대로 진행하세요
# use mysql;

# 현재 패스워드 설정 관련 내용 리스트
# select host,user,authentication_string from user;

# 새로운 패스워드 설정
# alter user 'root'@'localhost' identified with mysql_native_password by 'new_password_you_want';

# db 접속
# docker exec -it mysql mysql -p

#######################################
# 여기는 디렉토리 설정까지
#
# version: '3'
# services:
#   db:
#     image: mysql:latest
#     container_name: mysql-server
#     ports:
#       - '3306:3306'
#     environment:
#       MYSQL_ROOT_PASSWORD: 1225
#     command: # 명령어 실행
#       - --character-set-server=utf8mb4
#       - --collation-server=utf8mb4_unicode_ci
#     volumes:
#       - ./data/:/var/lib/mysql # -v 옵션 (디렉토리 마운트 설정)
